### ISSUE TITLE
Merge into baritone

### ISSUE THREAD

**Issue by UltraBlackLinux** [TheGreatRambler/EpicBaritone#1]
Hey there,
I think this would be a really great addition into Baritone! I just tried building it to see for myself how well it works, but gradle wants java 8 and sponge wants java 10, so I couldn't get it to build.
From the description of this repo I have to guess that it works quite well, so what about PRing that into official baritone? It would need some work to move it to the new fabric and forge compatible baritone api but I think it would be really nice!
Thanks!

**Comment by TheGreatRambler** [comment]
Unfortunately it became clear it was prohibitively expensive to run A star or other pathing algorithms on the absolutely gigantic number of possible states when you increase the number of possible states per tick from 8 or so to 100+. I didn't get it working as a result. I can imagine there are approaches to fixing this but I've moved on to other projects since
